#!/usr/bin/env python
"""Generate runs/view_all_poses.pml: receptor + every docked rank*.pdb pose on disk,
colored by docking score (green=best/most-negative -> yellow -> red=worst).

Run with: /Users/bb/.local/share/mamba/envs/researchia/bin/python research/gen_view_all_poses.py
"""
import re
from pathlib import Path

REPO = Path("/Users/bb/repos/hackathons/ebolathon")
RUNS = REPO / "runs"
OUT = RUNS / "view_all_poses.pml"

RANK_RE = re.compile(r"rank(\d+)_(-?\d+(?:\.\d+)?)\.pdb$")


def ramp(frac):
    """frac in [0,1]: 0 -> green (best), 0.5 -> yellow, 1 -> red (worst)."""
    if frac < 0.5:
        t = frac / 0.5
        r, g, b = t, 1.0, 0.0
    else:
        t = (frac - 0.5) / 0.5
        r, g, b = 1.0, 1.0 - t, 0.0
    return round(r, 3), round(g, 3), round(b, 3)


def collect():
    poses, seen = [], set()
    for p in sorted(RUNS.rglob("rank*.pdb")):
        if p.name == "receptor.pdb":
            continue
        m = RANK_RE.search(p.name)
        if not m:
            continue
        if p.name in seen:  # dedupe exact-duplicate filenames
            continue
        seen.add(p.name)
        poses.append({
            "path": str(p.resolve()),
            "rank": int(m.group(1)),
            "score": float(m.group(2)),
            "run": p.parent.name,
        })
    return poses


def pick_receptor(poses):
    counts = {}
    for pose in poses:
        counts[pose["run"]] = counts.get(pose["run"], 0) + 1
    best_run = max(counts, key=counts.get)
    return (RUNS / best_run / "receptor.pdb").resolve(), best_run


def safe(name):
    return re.sub(r"[^0-9A-Za-z_]", "_", name)


def main():
    poses = collect()
    if not poses:
        raise SystemExit("No rank*.pdb poses found under runs/")

    receptor, best_run = pick_receptor(poses)
    scores = [p["score"] for p in poses]
    smin, smax = min(scores), max(scores)  # smin=best(green), smax=worst(red)
    span = (smax - smin) or 1.0

    # object names, unique
    used = set()
    for p in poses:
        base = f"pose_{safe(p['run'])}_r{p['rank']}_{safe(f'{p['score']:.2f}')}"
        name = base
        i = 1
        while name in used:
            name = f"{base}_{i}"
            i += 1
        used.add(name)
        p["obj"] = name

    runs_used = sorted({p["run"] for p in poses})
    L = []
    L.append("# view_all_poses.pml  -- auto-generated by research/gen_view_all_poses.py")
    L.append("# Receptor (glycoprotein) + EVERY docked rank*.pdb pose on disk, across all runs.")
    L.append("# NOTE: these are the top-K EXPORTED poses per run (geometry), NOT every docked")
    L.append("#       molecule -- the bulk of the screen is scores-only with no exported pose.")
    L.append(f"# Poses: {len(poses)}   Runs: {', '.join(runs_used)}")
    L.append(f"# Score range (kcal/mol, lower=better): best {smin:.2f} (green) -> worst {smax:.2f} (red)")
    L.append("# Color ramp: green = best/most-negative, yellow = mid, red = worst.")
    L.append(f"# Open with:  pymol {OUT}")
    L.append("")
    L.append("reinitialize")
    L.append("bg_color white")
    L.append("set ray_shadows, 0")
    L.append("")
    L.append("# ---- receptor (shared coordinate frame; from run with most poses) ----")
    L.append(f"load {receptor}, receptor")
    L.append("hide everything, receptor")
    L.append("show cartoon, receptor")
    L.append("color grey70, receptor")
    L.append("set cartoon_transparency, 0.15, receptor")
    L.append("")
    L.append("# ---- docked poses (sticks, colored by score) ----")

    # emit best->worst so grouping/order is stable
    for p in sorted(poses, key=lambda x: x["score"]):
        frac = (p["score"] - smin) / span
        r, g, b = ramp(frac)
        col = f"col_{p['obj']}"
        L.append(f"load {p['path']}, {p['obj']}")
        L.append(f"hide everything, {p['obj']}")
        L.append(f"show sticks, {p['obj']}")
        L.append(f"set_color {col}, [{r}, {g}, {b}]")
        L.append(f"color {col}, {p['obj']}")
    L.append("")
    L.append("group poses, pose_*")
    L.append("")
    L.append("# ---- label the best ~10 poses with their score ----")
    for p in sorted(poses, key=lambda x: x["score"])[:10]:
        L.append(f'label first ({p["obj"]}), "{p["score"]:.2f}"')
    L.append("set label_size, 14")
    L.append("set label_color, black")
    L.append("")
    L.append("# ---- pocket residues within 5 A of any pose ----")
    L.append("select pocket, byres (receptor within 5 of poses)")
    L.append("show lines, pocket")
    L.append("deselect")
    L.append("")
    L.append("zoom poses, 6")
    L.append("")

    OUT.write_text("\n".join(L) + "\n")
    print(f"Wrote {OUT}")
    print(f"Poses: {len(poses)}  Receptor from: {best_run}")
    print(f"Runs: {runs_used}")
    print(f"Score best->worst: {smin:.2f} -> {smax:.2f}")


if __name__ == "__main__":
    main()
