# view_all_poses.pml  -- auto-generated by research/gen_view_all_poses.py
# Receptor (glycoprotein) + EVERY docked rank*.pdb pose on disk, across all runs.
# NOTE: these are the top-K EXPORTED poses per run (geometry), NOT every docked
#       molecule -- the bulk of the screen is scores-only with no exported pose.
# Poses: 27   Runs: glycoprotein_t0r_100, glycoprotein_t0r_trial
# Score range (kcal/mol, lower=better): best -9.20 (green) -> worst -7.30 (red)
# Color ramp: green = best/most-negative, yellow = mid, red = worst.
# Open with:  pymol /Users/bb/repos/hackathons/ebolathon/runs/view_all_poses.pml

reinitialize
bg_color white
set ray_shadows, 0

# ---- receptor (shared coordinate frame; from run with most poses) ----
load /Users/bb/repos/hackathons/ebolathon/runs/glycoprotein_t0r_100/receptor.pdb, receptor
hide everything, receptor
show cartoon, receptor
color grey70, receptor
set cartoon_transparency, 0.15, receptor

# ---- docked poses (sticks, colored by score) ----
load /Users/bb/repos/hackathons/ebolathon/runs/glycoprotein_t0r_100/rank1_-9.20.pdb, pose_glycoprotein_t0r_100_r1__9_20
hide everything, pose_glycoprotein_t0r_100_r1__9_20
show sticks, pose_glycoprotein_t0r_100_r1__9_20
set_color col_pose_glycoprotein_t0r_100_r1__9_20, [0.0, 1.0, 0.0]
color col_pose_glycoprotein_t0r_100_r1__9_20, pose_glycoprotein_t0r_100_r1__9_20
load /Users/bb/repos/hackathons/ebolathon/runs/glycoprotein_t0r_100/rank2_-8.70.pdb, pose_glycoprotein_t0r_100_r2__8_70
hide everything, pose_glycoprotein_t0r_100_r2__8_70
show sticks, pose_glycoprotein_t0r_100_r2__8_70
set_color col_pose_glycoprotein_t0r_100_r2__8_70, [0.526, 1.0, 0.0]
color col_pose_glycoprotein_t0r_100_r2__8_70, pose_glycoprotein_t0r_100_r2__8_70
load /Users/bb/repos/hackathons/ebolathon/runs/glycoprotein_t0r_100/rank1_-8.50.pdb, pose_glycoprotein_t0r_100_r1__8_50
hide everything, pose_glycoprotein_t0r_100_r1__8_50
show sticks, pose_glycoprotein_t0r_100_r1__8_50
set_color col_pose_glycoprotein_t0r_100_r1__8_50, [0.737, 1.0, 0.0]
color col_pose_glycoprotein_t0r_100_r1__8_50, pose_glycoprotein_t0r_100_r1__8_50
load /Users/bb/repos/hackathons/ebolathon/runs/glycoprotein_t0r_100/rank2_-8.50.pdb, pose_glycoprotein_t0r_100_r2__8_50
hide everything, pose_glycoprotein_t0r_100_r2__8_50
show sticks, pose_glycoprotein_t0r_100_r2__8_50
set_color col_pose_glycoprotein_t0r_100_r2__8_50, [0.737, 1.0, 0.0]
color col_pose_glycoprotein_t0r_100_r2__8_50, pose_glycoprotein_t0r_100_r2__8_50
load /Users/bb/repos/hackathons/ebolathon/runs/glycoprotein_t0r_100/rank3_-8.50.pdb, pose_glycoprotein_t0r_100_r3__8_50
hide everything, pose_glycoprotein_t0r_100_r3__8_50
show sticks, pose_glycoprotein_t0r_100_r3__8_50
set_color col_pose_glycoprotein_t0r_100_r3__8_50, [0.737, 1.0, 0.0]
color col_pose_glycoprotein_t0r_100_r3__8_50, pose_glycoprotein_t0r_100_r3__8_50
load /Users/bb/repos/hackathons/ebolathon/runs/glycoprotein_t0r_100/rank2_-8.40.pdb, pose_glycoprotein_t0r_100_r2__8_40
hide everything, pose_glycoprotein_t0r_100_r2__8_40
show sticks, pose_glycoprotein_t0r_100_r2__8_40
set_color col_pose_glycoprotein_t0r_100_r2__8_40, [0.842, 1.0, 0.0]
color col_pose_glycoprotein_t0r_100_r2__8_40, pose_glycoprotein_t0r_100_r2__8_40
load /Users/bb/repos/hackathons/ebolathon/runs/glycoprotein_t0r_100/rank3_-8.40.pdb, pose_glycoprotein_t0r_100_r3__8_40
hide everything, pose_glycoprotein_t0r_100_r3__8_40
show sticks, pose_glycoprotein_t0r_100_r3__8_40
set_color col_pose_glycoprotein_t0r_100_r3__8_40, [0.842, 1.0, 0.0]
color col_pose_glycoprotein_t0r_100_r3__8_40, pose_glycoprotein_t0r_100_r3__8_40
load /Users/bb/repos/hackathons/ebolathon/runs/glycoprotein_t0r_100/rank4_-8.40.pdb, pose_glycoprotein_t0r_100_r4__8_40
hide everything, pose_glycoprotein_t0r_100_r4__8_40
show sticks, pose_glycoprotein_t0r_100_r4__8_40
set_color col_pose_glycoprotein_t0r_100_r4__8_40, [0.842, 1.0, 0.0]
color col_pose_glycoprotein_t0r_100_r4__8_40, pose_glycoprotein_t0r_100_r4__8_40
load /Users/bb/repos/hackathons/ebolathon/runs/glycoprotein_t0r_100/rank3_-8.20.pdb, pose_glycoprotein_t0r_100_r3__8_20
hide everything, pose_glycoprotein_t0r_100_r3__8_20
show sticks, pose_glycoprotein_t0r_100_r3__8_20
set_color col_pose_glycoprotein_t0r_100_r3__8_20, [1.0, 0.947, 0.0]
color col_pose_glycoprotein_t0r_100_r3__8_20, pose_glycoprotein_t0r_100_r3__8_20
load /Users/bb/repos/hackathons/ebolathon/runs/glycoprotein_t0r_100/rank4_-8.20.pdb, pose_glycoprotein_t0r_100_r4__8_20
hide everything, pose_glycoprotein_t0r_100_r4__8_20
show sticks, pose_glycoprotein_t0r_100_r4__8_20
set_color col_pose_glycoprotein_t0r_100_r4__8_20, [1.0, 0.947, 0.0]
color col_pose_glycoprotein_t0r_100_r4__8_20, pose_glycoprotein_t0r_100_r4__8_20
load /Users/bb/repos/hackathons/ebolathon/runs/glycoprotein_t0r_100/rank5_-8.20.pdb, pose_glycoprotein_t0r_100_r5__8_20
hide everything, pose_glycoprotein_t0r_100_r5__8_20
show sticks, pose_glycoprotein_t0r_100_r5__8_20
set_color col_pose_glycoprotein_t0r_100_r5__8_20, [1.0, 0.947, 0.0]
color col_pose_glycoprotein_t0r_100_r5__8_20, pose_glycoprotein_t0r_100_r5__8_20
load /Users/bb/repos/hackathons/ebolathon/runs/glycoprotein_t0r_100/rank4_-8.10.pdb, pose_glycoprotein_t0r_100_r4__8_10
hide everything, pose_glycoprotein_t0r_100_r4__8_10
show sticks, pose_glycoprotein_t0r_100_r4__8_10
set_color col_pose_glycoprotein_t0r_100_r4__8_10, [1.0, 0.842, 0.0]
color col_pose_glycoprotein_t0r_100_r4__8_10, pose_glycoprotein_t0r_100_r4__8_10
load /Users/bb/repos/hackathons/ebolathon/runs/glycoprotein_t0r_100/rank5_-8.10.pdb, pose_glycoprotein_t0r_100_r5__8_10
hide everything, pose_glycoprotein_t0r_100_r5__8_10
show sticks, pose_glycoprotein_t0r_100_r5__8_10
set_color col_pose_glycoprotein_t0r_100_r5__8_10, [1.0, 0.842, 0.0]
color col_pose_glycoprotein_t0r_100_r5__8_10, pose_glycoprotein_t0r_100_r5__8_10
load /Users/bb/repos/hackathons/ebolathon/runs/glycoprotein_t0r_100/rank6_-8.10.pdb, pose_glycoprotein_t0r_100_r6__8_10
hide everything, pose_glycoprotein_t0r_100_r6__8_10
show sticks, pose_glycoprotein_t0r_100_r6__8_10
set_color col_pose_glycoprotein_t0r_100_r6__8_10, [1.0, 0.842, 0.0]
color col_pose_glycoprotein_t0r_100_r6__8_10, pose_glycoprotein_t0r_100_r6__8_10
load /Users/bb/repos/hackathons/ebolathon/runs/glycoprotein_t0r_100/rank5_-8.00.pdb, pose_glycoprotein_t0r_100_r5__8_00
hide everything, pose_glycoprotein_t0r_100_r5__8_00
show sticks, pose_glycoprotein_t0r_100_r5__8_00
set_color col_pose_glycoprotein_t0r_100_r5__8_00, [1.0, 0.737, 0.0]
color col_pose_glycoprotein_t0r_100_r5__8_00, pose_glycoprotein_t0r_100_r5__8_00
load /Users/bb/repos/hackathons/ebolathon/runs/glycoprotein_t0r_100/rank6_-8.00.pdb, pose_glycoprotein_t0r_100_r6__8_00
hide everything, pose_glycoprotein_t0r_100_r6__8_00
show sticks, pose_glycoprotein_t0r_100_r6__8_00
set_color col_pose_glycoprotein_t0r_100_r6__8_00, [1.0, 0.737, 0.0]
color col_pose_glycoprotein_t0r_100_r6__8_00, pose_glycoprotein_t0r_100_r6__8_00
load /Users/bb/repos/hackathons/ebolathon/runs/glycoprotein_t0r_100/rank7_-8.00.pdb, pose_glycoprotein_t0r_100_r7__8_00
hide everything, pose_glycoprotein_t0r_100_r7__8_00
show sticks, pose_glycoprotein_t0r_100_r7__8_00
set_color col_pose_glycoprotein_t0r_100_r7__8_00, [1.0, 0.737, 0.0]
color col_pose_glycoprotein_t0r_100_r7__8_00, pose_glycoprotein_t0r_100_r7__8_00
load /Users/bb/repos/hackathons/ebolathon/runs/glycoprotein_t0r_100/rank8_-8.00.pdb, pose_glycoprotein_t0r_100_r8__8_00
hide everything, pose_glycoprotein_t0r_100_r8__8_00
show sticks, pose_glycoprotein_t0r_100_r8__8_00
set_color col_pose_glycoprotein_t0r_100_r8__8_00, [1.0, 0.737, 0.0]
color col_pose_glycoprotein_t0r_100_r8__8_00, pose_glycoprotein_t0r_100_r8__8_00
load /Users/bb/repos/hackathons/ebolathon/runs/glycoprotein_t0r_100/rank9_-8.00.pdb, pose_glycoprotein_t0r_100_r9__8_00
hide everything, pose_glycoprotein_t0r_100_r9__8_00
show sticks, pose_glycoprotein_t0r_100_r9__8_00
set_color col_pose_glycoprotein_t0r_100_r9__8_00, [1.0, 0.737, 0.0]
color col_pose_glycoprotein_t0r_100_r9__8_00, pose_glycoprotein_t0r_100_r9__8_00
load /Users/bb/repos/hackathons/ebolathon/runs/glycoprotein_t0r_100/rank10_-7.90.pdb, pose_glycoprotein_t0r_100_r10__7_90
hide everything, pose_glycoprotein_t0r_100_r10__7_90
show sticks, pose_glycoprotein_t0r_100_r10__7_90
set_color col_pose_glycoprotein_t0r_100_r10__7_90, [1.0, 0.632, 0.0]
color col_pose_glycoprotein_t0r_100_r10__7_90, pose_glycoprotein_t0r_100_r10__7_90
load /Users/bb/repos/hackathons/ebolathon/runs/glycoprotein_t0r_trial/rank2_-7.90.pdb, pose_glycoprotein_t0r_trial_r2__7_90
hide everything, pose_glycoprotein_t0r_trial_r2__7_90
show sticks, pose_glycoprotein_t0r_trial_r2__7_90
set_color col_pose_glycoprotein_t0r_trial_r2__7_90, [1.0, 0.632, 0.0]
color col_pose_glycoprotein_t0r_trial_r2__7_90, pose_glycoprotein_t0r_trial_r2__7_90
load /Users/bb/repos/hackathons/ebolathon/runs/glycoprotein_t0r_100/rank8_-7.80.pdb, pose_glycoprotein_t0r_100_r8__7_80
hide everything, pose_glycoprotein_t0r_100_r8__7_80
show sticks, pose_glycoprotein_t0r_100_r8__7_80
set_color col_pose_glycoprotein_t0r_100_r8__7_80, [1.0, 0.526, 0.0]
color col_pose_glycoprotein_t0r_100_r8__7_80, pose_glycoprotein_t0r_100_r8__7_80
load /Users/bb/repos/hackathons/ebolathon/runs/glycoprotein_t0r_100/rank9_-7.80.pdb, pose_glycoprotein_t0r_100_r9__7_80
hide everything, pose_glycoprotein_t0r_100_r9__7_80
show sticks, pose_glycoprotein_t0r_100_r9__7_80
set_color col_pose_glycoprotein_t0r_100_r9__7_80, [1.0, 0.526, 0.0]
color col_pose_glycoprotein_t0r_100_r9__7_80, pose_glycoprotein_t0r_100_r9__7_80
load /Users/bb/repos/hackathons/ebolathon/runs/glycoprotein_t0r_trial/rank1_-7.70.pdb, pose_glycoprotein_t0r_trial_r1__7_70
hide everything, pose_glycoprotein_t0r_trial_r1__7_70
show sticks, pose_glycoprotein_t0r_trial_r1__7_70
set_color col_pose_glycoprotein_t0r_trial_r1__7_70, [1.0, 0.421, 0.0]
color col_pose_glycoprotein_t0r_trial_r1__7_70, pose_glycoprotein_t0r_trial_r1__7_70
load /Users/bb/repos/hackathons/ebolathon/runs/glycoprotein_t0r_100/rank10_-7.40.pdb, pose_glycoprotein_t0r_100_r10__7_40
hide everything, pose_glycoprotein_t0r_100_r10__7_40
show sticks, pose_glycoprotein_t0r_100_r10__7_40
set_color col_pose_glycoprotein_t0r_100_r10__7_40, [1.0, 0.105, 0.0]
color col_pose_glycoprotein_t0r_100_r10__7_40, pose_glycoprotein_t0r_100_r10__7_40
load /Users/bb/repos/hackathons/ebolathon/runs/glycoprotein_t0r_100/rank9_-7.40.pdb, pose_glycoprotein_t0r_100_r9__7_40
hide everything, pose_glycoprotein_t0r_100_r9__7_40
show sticks, pose_glycoprotein_t0r_100_r9__7_40
set_color col_pose_glycoprotein_t0r_100_r9__7_40, [1.0, 0.105, 0.0]
color col_pose_glycoprotein_t0r_100_r9__7_40, pose_glycoprotein_t0r_100_r9__7_40
load /Users/bb/repos/hackathons/ebolathon/runs/glycoprotein_t0r_100/rank10_-7.30.pdb, pose_glycoprotein_t0r_100_r10__7_30
hide everything, pose_glycoprotein_t0r_100_r10__7_30
show sticks, pose_glycoprotein_t0r_100_r10__7_30
set_color col_pose_glycoprotein_t0r_100_r10__7_30, [1.0, 0.0, 0.0]
color col_pose_glycoprotein_t0r_100_r10__7_30, pose_glycoprotein_t0r_100_r10__7_30

group poses, pose_*

# ---- label the best ~10 poses with their score ----
label first (pose_glycoprotein_t0r_100_r1__9_20), "-9.20"
label first (pose_glycoprotein_t0r_100_r2__8_70), "-8.70"
label first (pose_glycoprotein_t0r_100_r1__8_50), "-8.50"
label first (pose_glycoprotein_t0r_100_r2__8_50), "-8.50"
label first (pose_glycoprotein_t0r_100_r3__8_50), "-8.50"
label first (pose_glycoprotein_t0r_100_r2__8_40), "-8.40"
label first (pose_glycoprotein_t0r_100_r3__8_40), "-8.40"
label first (pose_glycoprotein_t0r_100_r4__8_40), "-8.40"
label first (pose_glycoprotein_t0r_100_r3__8_20), "-8.20"
label first (pose_glycoprotein_t0r_100_r4__8_20), "-8.20"
set label_size, 14
set label_color, black

# ---- pocket residues within 5 A of any pose ----
select pocket, byres (receptor within 5 of poses)
show lines, pocket
deselect

zoom poses, 6

